name: Publish examples
on:
  push:
    branches:
      - master
jobs:
  publish_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Central System 1.6 example
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ldonini/ocpp1.6-central-system:latest
          file: example/1.6/cs/Dockerfile
          context: .
      - name: Build Charge Point 1.6 example
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ldonini/ocpp1.6-charge-point:latest
          file: example/1.6/cp/Dockerfile
          context: .
