name: Release examples
on:
  release:
    types: [published,prereleased]
jobs:
  release_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Release Central System 1.6 example
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ldonini/ocpp1.6-central-system:${{ github.event.release.tag_name }}
          file: example/1.6/cs/Dockerfile
          context: .
      - name: Release Charge Point 1.6 example
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ldonini/ocpp1.6-charge-point:${{ github.event.release.tag_name }}
          file: example/1.6/cp/Dockerfile
          context: .
